import re

with open(r'C:\Users\ksj1388\OneDrive\Desktop\VPTRADEBOT\vptradebot.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the VPLineIndicator class and the ChartWidget class after it
start_idx = None
end_idx = None

for i, line in enumerate(lines):
    if 'class VPLineIndicator:' in line and 'class VPLineIndicator:' not in str(lines[max(0,i-5):i]):
        start_idx = i
        break

for i, line in enumerate(lines):
    if i > start_idx and 'class ChartWidget(QWidget):' in line:
        end_idx = i
        break

print(f"Start: {start_idx}, End: {end_idx}")

# Replacement class
replacement = [
    '# ============================================================\n',
    '#      VP Line Indicator - Volume Profile Auto [line] v2\n',
    '# ============================================================\n\n',
    'class VPLineIndicator:\n',
    '    def __init__(self, plot):\n',
    '        self.plot = plot\n',
    '        self._items = []\n',
    '        self._a_lines = []\n',
    '        self._a_vol = []\n',
    '        self._a_box = []\n',
    '        self._l_poc = None\n',
    '        self.parts = 25\n',
    '        self.max_width = 15\n',
    '        self.max_lines = 500\n',
    '        self.c_vol_h = "#ff8800"\n',
    '        self.c_vol = "#0088ff"\n',
    '        self.c_poc = "#ff0000"\n',
    '        self._t_h = 86400000\n',
    '        self._t_l = 3600000\n\n',
    '    @staticmethod\n',
    '    def _get_xy(ln):\n',
    '        if not hasattr(ln, "getData"):\n',
    '            return np.array([0]), np.array([0])\n',
    '        try:\n',
    '            x_data = ln.getData()[0]\n',
    '            y_data = ln.getData()[1]\n',
    '            if x_data is None or y_data is None:\n',
    '                return np.array([0]), np.array([0])\n',
    '            return np.array(x_data), np.array(y_data)\n',
    '        except:\n',
    '            return np.array([0]), np.array([0])\n\n',
    '    def clear_all(self):\n',
    '        for item in self._items:\n',
    '            self.plot.removeItem(item)\n',
    '        self._items.clear()\n',
    '        self._a_lines.clear()\n',
    '        self._a_vol.clear()\n',
    '        self._a_box.clear()\n',
    '        if self._l_poc:\n',
    '            self.plot.removeItem(self._l_poc)\n',
    '            self._l_poc = None\n\n',
    '    def _tf_to_ms(self, tf_str):\n',
    '        mapping = {\n',
    '            "1": 60000, "3": 180000, "5": 300000, "10": 600000,\n',
    '            "15": 900000, "30": 1800000, "60": 3600000, "120": 7200000,\n',
    '            "180": 10800000, "240": 14400000, "360": 21600000, "720": 43200000,\n',
    '            "1D": 86400000, "3D": 259200000, "1W": 604800000,\n',
    '            "1M": 2592000000, "1Y": 31536000000,\n',
    '            "M1": 60000, "M5": 300000, "M15": 900000, "M30": 1800000,\n',
    '            "H1": 3600000, "H4": 14400000, "D1": 86400000,\n',
    '            "W1": 604800000, "MN": 2592000000,\n',
    '        }\n',
    '        return mapping.get(tf_str, 3600000)\n\n',
    '    def _auto_htf(self, current_tf):\n',
    '        if current_tf in ["MN", "W1"]: return "1M"\n',
    '        if current_tf in ["D1"]: return "1W"\n',
    '        if current_tf in ["H1", "H4"]: return "1D"\n',
    '        if current_tf in ["M5", "M15", "M30"]: return "60"\n',
    '        if current_tf in ["M1"]: return "1"\n',
    '        return "60"\n\n',
    '    def _auto_ltf(self, current_tf):\n',
    '        if current_tf in ["MN", "W1", "D1"]: return "D"\n',
    '        if current_tf in ["H1", "H4"]: return "H1"\n',
    '        if current_tf in ["M5", "M15", "M30"]: return "60"\n',
    '        if current_tf in ["M1"]: return "1"\n',
    '        return "60"\n\n',
    '    def update_settings(self, parts, max_width, ltf_str, htf_str, current_tf, is_auto=True):\n',
    '        self.parts = parts\n',
    '        self.max_width = max_width\n',
    '        self.is_auto = is_auto\n',
    '        self.ltf_str = ltf_str\n',
    '        self.htf_str = htf_str\n',
    '        self.current_tf = current_tf\n',
    '        self.is_auto = is_auto\n',
    '        if is_auto:\n',
    '            self._t_h = self._tf_to_ms(self._auto_htf(current_tf))\n',
    '            self._t_l = self._tf_to_ms(self._auto_ltf(current_tf))\n',
    '        else:\n',
    '            self._t_h = self._tf_to_ms(htf_str if htf_str != "Auto" else self._auto_htf(current_tf))\n',
    '            self._t_l = self._tf_to_ms(ltf_str if ltf_str != "Auto" else self._auto_ltf(current_tf))\n\n',
    '    def draw(self, times, high, low, close, volume, bar_index):\n',
    '        if len(times) < 2:\n',
    '            return\n',
    '        cur_high = high[-1]\n',
    '        cur_low = low[-1]\n',
    '        cur_vol = volume[-1]\n',
    '        if self._t_l == 0:\n',
    '            return\n',
    '        i_size = self.parts\n',
    '        aMax = self.max_lines\n',
    '        if not self._a_lines:\n',
    '            self._a_lines = []\n',
    '            self._a_vol = []\n',
    '            self._a_box = []\n',
    '        chT_H = len(self._a_lines) > 0 and len(times) > len(self._a_lines)\n',
    '        if not self._a_lines:\n',
    '            hi = high[-1]\n',
    '            lo = low[-1]\n',
    '            if hi > lo:\n',
    '                step = (hi - lo) / self.parts\n',
    '                for j in range(self.parts):\n',
    '                    y1 = hi - (hi - lo) / self.parts * j\n',
    '                    y2 = hi - (hi - lo) / self.parts * (j + 1)\n',
    '                    ln = pg.PlotDataItem([times[-1], times[-1]], [y1, y2], \n',
    '                                         pen=pg.mkPen(self.c_vol, width=1))\n',
    '                    self.plot.addItem(ln, ignoreBounds=True)\n',
    '                    self._a_lines.insert(0, ln)\n',
    '                    self._items.append(ln)\n',
    '                    self._a_vol.insert(0, 0.0)\n',
    '                from PyQt5.QtWidgets import QGraphicsRectItem\n',
    '                from PyQt5.QtCore import QRectF\n',
    '                box = QGraphicsRectItem()\n',
    '                box.setRect(QRectF(times[-1], lo, 0, hi - lo))\n',
    '                box.setBrush(pg.mkBrush(0, 0, 255, 20))\n',
    '                box.setPen(pg.mkPen(None))\n',
    '                self.plot.addItem(box, ignoreBounds=True)\n',
    '                self._a_box.insert(0, box)\n',
    '                self._items.append(box)\n',
    '                while len(self._a_lines) > self.max_lines:\n',
    '                    old = self._a_lines.pop()\n',
    '                    self.plot.removeItem(old)\n',
    '                    self._a_vol.pop()\n',
    '                while len(self._a_box) > int(self.max_lines / self.parts) + 1:\n',
    '                    old_box = self._a_box.pop()\n',
    '                    self.plot.removeItem(old_box)\n',
    '        if not self._a_lines:\n',
    '            return\n',
    '        hi = self._a_lines[0].getData()[1][0] if len(self._a_lines[0].getData()[1]) > 0 else high[-1]\n',
    '        lo = self._a_lines[-1].getData()[1][1] if len(self._a_lines[-1].getData()[1]) > 1 else low[-1]\n',
    '        if self._a_box:\n',
    '            box = self._a_box[0]\n',
    '            box.setRect(box.rect().x(), box.rect().y(), \n',
    '                       times[-1] - box.rect().x(), box.rect().height())\n',
    '        if self._l_poc:\n',
    '            x_poc, y_poc = self._get_xy(self._l_poc)\n',
    '            if len(x_poc) > 0 and len(y_poc) > 0:\n',
    '                self._l_poc.setData([float(x_poc[0]), times[-1]], \n',
    '                                    [float(y_poc[0]), float(y_poc[0])])\n',
    '        if high[-1] > hi:\n',
    '            for j in range(self.parts):\n',
    '                if j < len(self._a_lines):\n',
    '                    ln = self._a_lines[j]\n',
    '                    x_data, _ = self._get_xy(ln)\n',
    '                    if len(x_data) > 0:\n',
    '                        ln.setData([float(x_data[0]), times[-1]], [high[-1], high[-1]])\n',
    '            hi = high[-1]\n',
    '            if self._a_box:\n',
    '                box = self._a_box[0]\n',
    '                box.setRect(box.rect().x(), box.rect().y(), box.rect().width(), high[-1] - box.rect().y())\n',
    '        if low[-1] < lo:\n',
    '            for j in range(self.parts):\n',
    '                if j < len(self._a_lines):\n',
    '                    ln = self._a_lines[j]\n',
    '                    x_data, _ = self._get_xy(ln)\n',
    '                    if len(x_data) > 0:\n',
    '                        ln.setData([float(x_data[0]), times[-1]], [low[-1], low[-1]])\n',
    '            lo = low[-1]\n',
    '            if self._a_box:\n',
    '                box = self._a_box[0]\n',
    '                box.setRect(box.rect().x(), low[-1], box.rect().width(), hi - low[-1])\n',
    '        for j in range(min(self.parts, len(self._a_lines))):\n',
    '            ln = self._a_lines[j]\n',
    '            x_data, y_data = self._get_xy(ln)\n',
    '            if len(y_data) < 2:\n',
    '                continue\n',
    '            y1 = float(y_data[0])\n',
    '            y2 = float(y_data[1])\n',
    '            if high[-1] >= y1 and low[-1] <= y2:\n',
    '                self._a_vol[j] += volume[-1]\n',
    '                width = max(1, int(self.max_width * self._a_vol[j] / max(self._a_vol) if max(self._a_vol) > 0 else 1))\n',
    '                ln.setPen(pg.mkPen(self.c_vol, width=width))\n',
    '        self._draw_poc()\n\n',
    '    def _draw_poc(self):\n',
    '        if not self._a_vol:\n',
    '            return\n',
    '        max_vol = max(self._a_vol)\n',
    '        idx = self._a_vol.index(max_vol)\n',
    '        if idx >= len(self._a_lines) - 1:\n',
    '            return\n',
    '        if self._l_poc:\n',
    '            self.plot.removeItem(self._l_poc)\n',
    '        ln1 = self._a_lines[idx]\n',
    '        ln2 = self._a_lines[idx + 1]\n',
    '        x1, y1 = self._get_xy(self._a_lines[idx])\n',
    '        x2, y2 = self._get_xy(self._a_lines[idx + 1])\n',
    '        if len(y1) == 0 or len(y2) == 0:\n',
    '            return\n',
    '        poc_y = (y1[0] + y2[0]) / 2\n',
    '        if len(x1) == 0:\n',
    '            return\n',
    '        x1_val = x1[0]\n',
    '        x2_val = (x1[-1] if len(x1) > 1 else x1[0]) + 100\n',
    '        self._l_poc = pg.PlotDataItem([x1_val, x1_val + 100], [poc_y, poc_y], \n',
    '                                      pen=pg.mkPen(self.c_poc, width=2))\n',
    '        self.plot.addItem(self._l_poc, ignoreBounds=True)\n',
    '        self._items.append(self._l_poc)\n\n',
    '    @staticmethod\n',
    '    def _get_xy(ln):\n',
    '        if not hasattr(ln, "getData"):\n',
    '            return np.array([0]), np.array([0])\n',
    '        try:\n',
    '            x_data = ln.getData()[0]\n',
    '            y_data = ln.getData()[1]\n',
    '            if x_data is None or y_data is None:\n',
    '                return np.array([0]), np.array([0])\n',
    '            return np.array(x_data), np.array(y_data)\n',
    '        except:\n',
    '            return np.array([0]), np.array([0])\n\n',
    'class ChartWidget(QWidget):\n',
]

# Replace the section
new_lines = lines[:start_idx] + replacement + lines[end_idx:]

with open(r'C:\Users\ksj1388\OneDrive\Desktop\VPTRADEBOT\vptradebot.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print('Done')
"